### ISSUE TITLE
Multicast Multiblock response with Etag not working with LwIP

### ISSUE THREAD

**Issue by cdurkin** [obgm/libcoap#1636]
## Environment

- Build System: Eclipse / MCUXpresso
- Hosted Environment: LwIP, FreeRTOS

## libcoap Configuration Summary

libcoap package version : "4.3.5"
libcoap package source : "4.3.5"
libcoap API version : "3"
libcoap ABI version : "3.2.0"
libcoap libtool SO version : "5.0.2"
libcoap DTLS lib extn : "-mbedtls"
host system : "x86_64-pc-linux-gnu"
build with server support : "yes"
build with client support : "yes"
build with proxy support : "yes"
build with IPv4 support : "yes"
build with IPv6 support : "yes"
build with Unix socket support : "yes"
build with TCP support : "yes"
build DTLS support : "yes"
--> Mbed TLS around : "yes" (found Mbed TLS without pkg-config)
MbedTLS_CFLAGS : ""
MbedTLS_LIBS : ""
build DTLS support : "no"
add default names : "yes"
build Observe Persist : "yes"
build using epoll : "yes"
enable small stack size : "no"
enable separate responses : "yes"
enable OSCORE support : "yes"
enable Q-Block support : "yes"
enable max logging level : "none"
enable thread safe code : "yes"
enable recursive lock check : "yes"
build doxygen pages : "no"
build man pages : "no"
build unit test binary : "no"
build examples : "yes"
install examples source : "yes"
build with gcov support : "no"
build shared library : "yes"
build static library : "yes"

My build include the patch https://github.com/obgm/libcoap/pull/1545

## Problem Description

I'm getting the following warning "Data body updated during receipt - new request started" and then a timeout waiting for the 2nd multicast response which i believe is being received but the callback into my application is not being invoked.

### Expected Behavior

I'm not entirely clear from https://datatracker.ietf.org/doc/html/rfc7959#section-2.8 what the restrictions on multicast multiblock are but non-multiblock (i.e. single block) is working and hence i assume multiblock response should work to. Or is this maybe something not supported by libcoap or not with "COAP_BLOCK_USE_LIBCOAP | COAP_BLOCK_SINGLE_BODY". Does Libcoap support this or would we need to not set "COAP_BLOCK_USE_LIBCOAP | COAP_BLOCK_SINGLE_BODY" and manage reconstructing multicast multiblock responses ourselves?

### Steps to reproduce

Send out a GET request on the multicast address (i.e. 224.0.1.187) where there are 2 servers running on the subnet both with there own instances of the resource in the GET request. The server always include a Etag in the response. The resource (on both servers) are large enough that it's triggers multiblock transfer.

### Code to reproduce this issue

I'm working on a embedded device using FreeRTOS and LwIP where we have one task for the CoAP client and one for the CoAP server. The server sets block mode i.e.

```c
coap_context_set_block_mode(coap_context, COAP_BLOCK_USE_LIBCOAP | COAP_BLOCK_SINGLE_BODY);
```

My client code starts a coap session as follows
```c
session = coap_new_client_session(coap_client_context, NULL, pstRequest->pstDst, COAP_PROTO_UDP);
```
where pstRequest->pstDst is for the test is set to the default CoAP Multicast address i.e. 224.0.1.187

We are using the default LwIP task (and hence CORE_LOCKING is off) and we have split the coap_recvc() and coap_udp_recvs() functions from coap_io_lwip.c in half so that we can serialise the message processing out to our coap client and server tasks. Hence we have replaced coap_recvc() with the following

```c
/**
 * Part 1 of replacement for coap_recvc()
 * Callback from lwIP when a packet was received for a client.
 *
 * This replaces the original coap_recvc in coap_io_lwip.c but is essentially
 * the same just split in two to pass the packet to our client task and have it
 * process the message. See coap_client_process_response()
 */
void coap_recvc(void *arg, struct udp_pcb *upcb, struct pbuf *p,
           const ip_addr_t *addr, u16_t port)
{
  coap_session_t *session = (coap_session_t *)arg;
  uCoAPClientMsgCtx_t ctx;

  (void)upcb; // unused param

  assert(session);
  LWIP_ASSERT("Proto not supported for LWIP", COAP_PROTO_NOT_RELIABLE(session->proto));

  if (p->len < 4) {
    /* Minimum size of CoAP header - ignore runt */
    return;
  }

  /*
   * allocate context for this. This will be freed in the coap client task,
   * or in the case of failure to enqueue, but the queu function below.
   */
  ctx.presponse = coap_malloc_type(COAP_RESPONSE, sizeof(stCoAPResponse_t));

  if (ctx.presponse != NULL)
  {
    ctx.presponse->p = p;
    ctx.presponse->psession = session;
    ctx.presponse->address.port = port;
    ctx.presponse->address.addr = *addr;

    /* Send packet to coap client task */
    Coap_PostToClient(eCoapClient_Response, ctx);
  }
}

/**
 * Part 2 of replacement for coap_recvc()
 * Process the received packet same as libcoap's own coap_io_lwip.c:coap_recvc()
 * does but from within our client task
 */
bool client_processResponse(stCoAPResponse_t* pcontext)
{
	coap_session_t *session = pcontext->psession;
	stReqContext_t * pstReqContext;
	struct pbuf *p = pcontext->p;
	unsigned char addr_str[24];
	int result = -1;

	assert(pcontext);
	assert(pcontext->p);
	assert(pcontext->psession);

	// we need to pass the source address of the received response to the our response handler
	// and there's no field in coap_pdu_t so we have to pass it through our request context we have stored at session->app
	pstReqContext = (stReqContext_t * )session->app;
	if(pstReqContext)
	{
		pstReqContext->pstSrcAddr = &pcontext->address;
	}
	else
	{
		coap_log_err("response arrived with no request context\n");
	}

	/* code below is taken from the original coap_recvc() in standard coap_io_lwip.c.
	 * Moved here so it can run in our coap client task rather than the lwip task.
	 */
	coap_pdu_t *pdu = NULL;
	coap_print_addr(&pcontext->address, addr_str, sizeof(addr_str));
	coap_log_info("*  %s: lwip:  recvc() %4d bytes from %s\n", coap_session_str(session), p->len, addr_str);
	if (session->proto == COAP_PROTO_DTLS) {
		if (session->tls) {
			result = coap_dtls_receive(session, p->payload, p->len);
			if (result < 0)
				goto error;
		}
		pbuf_free(p);
	} else {
		pdu = coap_pdu_from_pbuf(p);
		if (!pdu)
			goto error;

		if (!coap_pdu_parse(session->proto, p->payload, p->len, pdu)) {
			goto error;
		}
		coap_lock_lock(session->context, return);
		coap_dispatch(session->context, session, pdu);
		coap_lock_unlock(session->context);
	}
#if NO_SYS == 0
	sys_sem_signal(&coap_io_timeout_sem);
#endif /* NO_SYS == 0 */
	coap_delete_pdu(pdu);
	return true;

	error:
	/*
	 * https://rfc-editor.org/rfc/rfc7252#section-4.2 MUST send RST
	 * https://rfc-editor.org/rfc/rfc7252#section-4.3 MAY send RST
	 */
	if (session)
		coap_send_rst_lkd(session, pdu);
	coap_delete_pdu(pdu);
	return false;
}
```

## Debug Logs
Logs from the unit test runner and coap client FreeRTOS task

```
Running test 1: Mirrored GET Multicast Multiblock
expecting responses from 192.168.50.2 and 192.168.50.4
Jan 01 00:19:40.942 info[Cln] --> Request received
Jan 01 00:19:40.306 info[Cln] Send PDU (0x8001d394) GET 'datatest/container' #Test/0 mid:d440 etag:0x0
Jan 01 00:19:40.991 info[Cln] <-- Response received
Jan 01 00:19:40.046 info[Cln] *  [0.0.0.0]:52267 <-> [224.0.1.187]:5683 UDP : lwip:  recvc() 1043 bytes from [192.168.50.4]:5683
v:1 t:NON c:2.05 i:d440 {} [ ETag:0x12a600000001, Content-Format:application/json, Block2:0/M/1024, Size2:1929 ] :: '{"Step Inputs":false,"Inputx1":{"InputType":"Single Input","State":0,"Quality":0,"Timestamp":{"secs":0,"nsecs":0,"timequality"

Jan 01 00:19:40.553 info[Cln] <-- Response received
Jan 01 00:19:40.604 info[Cln] *  [0.0.0.0]:52267 <-> [224.0.1.187]:5683 UDP : lwip:  recvc() 1043 bytes from [192.168.50.2]:5683
v:1 t:NON c:2.05 i:d440 {} [ ETag:0x1a1100000001, Content-Format:application/json, Block2:0/M/1024, Size2:1929 ] :: '{"Step Inputs":false,"Inputx1":{"InputType":"Single Input","State":0,"Quality":0,"Timestamp":{"secs":0,"nsecs":0,"timequality"

Jan 01 00:19:40.820 Warn[___] Data body updated during receipt - new request started
Jan 01 00:19:40.543 info[Cln] <-- Response received
Jan 01 00:19:40.591 info[Cln] *  [0.0.0.0]:52267 <-> [224.0.1.187]:5683 UDP : lwip:  recvc()  931 bytes from [192.168.50.2]:5683
v:1 t:NON c:2.05 i:d441 {02000000000001} [ ETag:0x1a1100000001, Content-Format:application/json, Block2:1/_/1024, Size2:1929 ] :: 'mequality":0}},"Counterx2":{"InputType":"Double Counter","State":0,"LiveCount":0,"Quality":0,"Timestamp":{"secs"

Jan 01 00:19:40.327 info[Cln] <-- Response received
Jan 01 00:19:40.366 info[Cln] *  [0.0.0.0]:52267 <-> [224.0.1.187]:5683 UDP : lwip:  recvc() 1044 bytes from [192.168.50.4]:5683
v:1 t:NON c:2.05 i:d442 {02} [ ETag:0x12a600000001, Content-Format:application/json, Block2:0/M/1024, Size2:1929 ] :: '{"Step Inputs":false,"Inputx1":{"InputType":"Single Input","State":0,"Quality":0,"Timestamp":{"secs":0,"nsecs":0,"timequalit

Jan 01 00:19:40.500 info[Cln] <-- Response received
Jan 01 00:19:40.536 info[Cln] *  [0.0.0.0]:52267 <-> [224.0.1.187]:5683 UDP : lwip:  recvc() 1044 bytes from [192.168.50.2]:5683
v:1 t:NON c:2.05 i:d442 {02} [ ETag:0x1a1100000001, Content-Format:application/json, Block2:0/M/1024, Size2:1929 ] :: '{"Step Inputs":false,"Inputx1":{"InputType":"Single Input","State":0,"Quality":0,"Timestamp":{"secs":0,"nsecs":0,"timequalit

Jan 01 00:19:40.022 info[Cln] <-- Response received
Jan 01 00:19:40.056 info[Cln] *  [0.0.0.0]:52267 <-> [224.0.1.187]:5683 UDP : lwip:  recvc()  931 bytes from [192.168.50.4]:5683
v:1 t:NON c:2.05 i:d441 {02000000000001} [ ETag:0x12a600000001, Content-Format:application/json, Block2:1/_/1024, Size2:1929 ] :: 'mequality":0}},"Counterx2":{"InputType":"Double Counter","State":0,"LiveCount":0,"Quality":0,"Timestamp":{"secs"

Jan 01 00:19:40.325 Warn[___] Data body updated during receipt - new request started
Jan 01 00:19:40.046 info[Cln] <-- Response received
Jan 01 00:19:40.084 info[Cln] *  [0.0.0.0]:52267 <-> [224.0.1.187]:5683 UDP : lwip:  recvc() 1044 bytes from [192.168.50.4]:5683
v:1 t:NON c:2.05 i:d443 {03} [ ETag:0x12a600000001, Content-Format:application/json, Block2:0/M/1024, Size2:1929 ] :: '{"Step Inputs":false,"Inputx1":{"InputType":"Single Input","State":0,"Quality":0,"Timestamp":{"secs":0,"nsecs":0,"timequalit

Jan 01 00:19:40.524 info[Cln] <-- Response received
Jan 01 00:19:40.560 info[Cln] *  [0.0.0.0]:52267 <-> [224.0.1.187]:5683 UDP : lwip:  recvc() 1044 bytes from [192.168.50.2]:5683
v:1 t:NON c:2.05 i:d443 {03} [ ETag:0x1a1100000001, Content-Format:application/json, Block2:0/M/1024, Size2:1929 ] :: '{"Step Inputs":false,"Inputx1":{"InputType":"Single Input","State":0,"Quality":0,"Timestamp":{"secs":0,"nsecs":0,"timequalit

mirrored GET response timed out (2.000 sec)
../../Plugin_DataTest/tests/coap_tests.c:328:Mirrored GET Multicast Multiblock :FAIL: Expected -1 to be not equal to -1. Timeout / Empty Queue
[Test] tear down
```

## Other items if possible

I can see the warning is from coap_block.c line 3911 and i can see this is inside the "if (etag_opt)" block hence i suspect this is due to the Etags in the responses from the two servers being different, which is to be expected as they are 2 distinct resources and hence the multiblock transfer for each needs to be reconstructed separately.

**Comment by mrdeep1** [comment]
Thanks for raising this with all the research detail behind it.  I can confirm that I can reproduce it.

**Comment by mrdeep1** [comment]
@cdurkin I have with the general libcoap code been able to reproduce what you are seeing.  This is now fixed in #1645. Please check if this fixes what you were seeing. 

Apologies for the time taken to fix this, but it was not a simple fix.

**Comment by cdurkin** [comment]
Thanks very much for providing a fix, i tried including it as a patch but seems there was too many other changes so i had to merge the head of master into our build, it's passing all my other test so i believe i got this right but it still failing the 'multicast multiblock' test, and with the same issue i.e. still seeing the "Data body updated during receipt - new request started
" warning

Full logs >>>>>>>>>>

~~~~~~~~~~~~~~~~~~~~  Tests Start  ~~~~~~~~~~~~~~~~~~~~
Run: filter 'Multicast Multiblock'
--- Running set: CoAP ... all skipped
--- Running set: CoAP+JSON
Running test 1: Mirrored GET Multicast Multiblock
expecting responses from 192.168.100.1 and 192.168.100.2
Jan 01 00:00:53.657 dbg [___] ***[0.0.0.0]:52362 <-> [224.0.1.187]:5683 UDP : session 0x8004262c: created outgoing session
Jan 01 00:00:53.769 dbg [___] ***[0.0.0.0]:52362 <-> [224.0.1.187]:5683 UDP : session connected
Jan 01 00:00:53.812 dbg [___] ***[0.0.0.0]:52362 <-> [224.0.1.187]:5683 UDP : session max_retransmit set to 1
Jan 01 00:00:53.033 dbg [___] ** [0.0.0.0]:52362 <-> [224.0.1.187]:5683 UDP : lg_crcv 0x800049dc initialized - stateless token xxxxx00000000001
Jan 01 00:00:53.654 dbg [___] ***[224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : session 0x8004240c: new incoming session
Jan 01 00:00:53.695 dbg [___] ***EVENT: COAP_EVENT_SERVER_SESSION_NEW
v:1 t:NON c:GET i:56a8 {} [ Uri-Path:datatest, Uri-Path:container, 18:, 22:\x23\x54\x65\x73\x74, Request-Tag:0x08cdb800 ]

Jan 01 00:00:53.267 dbg [___] *  [0.0.0.0]:52362 <-> [224.0.1.187]:5683 UDP : netif: sent   37 bytes
v:1 t:NON c:GET i:56a8 {} [ Uri-Path:datatest, Uri-Path:container, 18:, 22:\x23\x54\x65\x73\x74, Request-Tag:0x08cdb800 ]

Jan 01 00:00:53.506 dbg [___] call custom handler for resource 'datatest/container' (3)
Jan 01 00:00:53.419 dbg [___] PDU presented by app.
v:1 t:NON c:2.05 i:56a8 {} [ ETag:0x1b7400000001, Content-Format:application/json ] :: '{"Step Inputs":false,"Inputx1":{"InputType":"Single Input","State":0,"Quality":0,"Timestamp":{"secs":0,"nsecs":0,"timequality":0}},"Inputx2":{"InputType":"

Jan 01 00:00:53.572 dbg [___] ** [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : lg_xmit 0x80007e10 initialized
Jan 01 00:00:53.802 dbg [___]    [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : mid=0x56a8: mcast response delayed for 0.034 secs
Jan 01 00:00:53.849 dbg [___] ** [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : mid=0x56a8: added to retransmit queue (34ms)
v:1 t:NON c:2.05 i:56a8 {} [ ETag:0x12f800000001, Content-Format:application/json, Block2:0/M/1024, Size2:1927 ] :: '{"Step Inputs":false,"Inputx1":{"InputType":"Single Input","State":0,"Quality":0,"Timestamp":{"secs":0,"nsecs":0,"timequality"

Jan 01 00:00:53.892 dbg [___] found Block option, block size is 1024, block nr. 0
v:1 t:NON c:GET i:56a9 {200000000001} [ Uri-Path:datatest, Uri-Path:container, 18:, 22:\x23\x54\x65\x73\x74, Block2:1/_/1024, Request-Tag:0x08cdb800 ]

Jan 01 00:00:53.662 dbg [___] found Block option, block size is 1024, block nr. 1, M 0
Jan 01 00:00:53.822 dbg [___]    [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : mid=0x56a9: mcast response delayed for 0.008 secs
Jan 01 00:00:53.868 dbg [___] ** [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : mid=0x56a9: added to retransmit queue (8ms)
Jan 01 00:00:53.229 dbg [___] *  [0.0.0.0]:52362 <-> [224.0.1.187]:5683 UDP : netif: sent   45 bytes
v:1 t:NON c:GET i:56a9 {200000000001} [ Uri-Path:datatest, Uri-Path:container, 18:, 22:\x23\x54\x65\x73\x74, Block2:1/_/1024, Request-Tag:0x08cdb800 ]

Jan 01 00:00:53.238 dbg [___] ***EVENT: COAP_EVENT_MSG_RETRANSMITTED
Jan 01 00:00:53.289 dbg [___] ** [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : mid=0x56a9: mcast delayed transmission
v:1 t:NON c:2.05 i:56a9 {200000000001} [ ETag:0x1b7400000001, Content-Format:application/json, Block2:1/_/1024, Size2:1927 ] :: 'mequality":0}},"Counterx2":{"InputType":"Double Counter","State":0,"LiveCount":0,"Quality":0,"Timestamp":{"secs":0

Jan 01 00:00:53.831 Warn[___] Data body updated during receipt - new request started
Jan 01 00:00:53.281 dbg [___] *  [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : netif: sent  928 bytes
v:1 t:NON c:2.05 i:56a9 {200000000001} [ ETag:0x1b7400000001, Content-Format:application/json, Block2:1/_/1024, Size2:1927 ] :: 'mequality":0}},"Counterx2":{"InputType":"Double Counter","State":0,"LiveCount":0,"Quality":0,"Timestamp":{"secs":0

Jan 01 00:00:53.430 dbg [___] ***EVENT: COAP_EVENT_MSG_RETRANSMITTED
Jan 01 00:00:53.466 dbg [___] ** [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : mid=0x56a8: mcast delayed transmission
Jan 01 00:00:53.759 dbg [___] *  [0.0.0.0]:52362 <-> [224.0.1.187]:5683 UDP : netif: sent   40 bytes
v:1 t:NON c:GET i:56aa {02} [ Uri-Path:datatest, Uri-Path:container, 18:, 22:\x23\x54\x65\x73\x74, Block2:0/_/1024, Request-Tag:0x08cdb800 ]

v:1 t:NON c:2.05 i:56a8 {} [ ETag:0x1b7400000001, Content-Format:application/json, Block2:0/M/1024, Size2:1927 ] :: '{"Step Inputs":false,"Inputx1":{"InputType":"Single Input","State":0,"Quality":0,"Timestamp":{"secs":0,"nsecs":0,"timequality"

Jan 01 00:00:53.257 dbg [___] *  [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : netif: sent 1043 bytes
v:1 t:NON c:2.05 i:56a8 {} [ ETag:0x1b7400000001, Content-Format:application/json, Block2:0/M/1024, Size2:1927 ] :: '{"Step Inputs":false,"Inputx1":{"InputType":"Single Input","State":0,"Quality":0,"Timestamp":{"secs":0,"nsecs":0,"timequality"

v:1 t:NON c:GET i:56aa {02} [ Uri-Path:datatest, Uri-Path:container, 18:, 22:\x23\x54\x65\x73\x74, Block2:0/_/1024, Request-Tag:0x08cdb800 ]

Jan 01 00:00:53.655 dbg [___] call custom handler for resource 'datatest/container' (3)
Jan 01 00:00:53.868 dbg [___] ** [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : lg_xmit 0x80007e10 released
Jan 01 00:00:53.906 dbg [___] ***EVENT: COAP_EVENT_XMIT_BLOCK_FAIL
Jan 01 00:00:53.951 dbg [___] PDU presented by app.
v:1 t:NON c:2.05 i:56aa {02} [ ETag:0x1b7400000001, Content-Format:application/json, Block2:0/M/1024 ] :: '{"Step Inputs":false,"Inputx1":{"InputType":"Single Input","State":0,"Quality":0,"Timestamp":{"secs":0,"nsecs":0,"timequality":0}},"Inpu

Jan 01 00:00:53.047 dbg [___] found Block option, block size is 1024, block nr. 0
Jan 01 00:00:53.063 dbg [___] ** [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : lg_xmit 0x80007e10 initialized
Jan 01 00:00:53.686 dbg [___]    [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : mid=0x56aa: mcast response delayed for 0.005 secs
Jan 01 00:00:53.733 dbg [___] ** [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : mid=0x56aa: added to retransmit queue (5ms)
v:1 t:NON c:GET i:56ab {400000000001} [ Uri-Path:datatest, Uri-Path:container, 18:, 22:\x23\x54\x65\x73\x74, Block2:1/_/1024, Request-Tag:0x08cdb800 ]

Jan 01 00:00:53.282 dbg [___] *  [0.0.0.0]:52362 <-> [224.0.1.187]:5683 UDP : netif: sent   45 bytes
v:1 t:NON c:GET i:56ab {400000000001} [ Uri-Path:datatest, Uri-Path:container, 18:, 22:\x23\x54\x65\x73\x74, Block2:1/_/1024, Request-Tag:0x08cdb800 ]

Jan 01 00:00:53.061 dbg [___] found Block option, block size is 1024, block nr. 1, M 0
Jan 01 00:00:53.624 dbg [___]    [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : mid=0x56ab: mcast response delayed for 0.032 secs
Jan 01 00:00:53.668 dbg [___] ** [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : mid=0x56ab: added to retransmit queue (32ms)
Jan 01 00:00:53.256 dbg [___] ***EVENT: COAP_EVENT_MSG_RETRANSMITTED
Jan 01 00:00:53.293 dbg [___] ** [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : mid=0x56aa: mcast delayed transmission
v:1 t:NON c:2.05 i:56aa {02} [ ETag:0x1b7400000001, Content-Format:application/json, Block2:0/M/1024, Size2:1927 ] :: '{"Step Inputs":false,"Inputx1":{"InputType":"Single Input","State":0,"Quality":0,"Timestamp":{"secs":0,"nsecs":0,"timequalit

Jan 01 00:00:53.776 dbg [___] ** [0.0.0.0]:52362 <-> [224.0.1.187]:5683 UDP : large body receive internal issue
Jan 01 00:00:53.936 dbg [___] *  [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : netif: sent 1044 bytes
v:1 t:NON c:2.05 i:56aa {02} [ ETag:0x1b7400000001, Content-Format:application/json, Block2:0/M/1024, Size2:1927 ] :: '{"Step Inputs":false,"Inputx1":{"InputType":"Single Input","State":0,"Quality":0,"Timestamp":{"secs":0,"nsecs":0,"timequalit

v:1 t:NON c:2.05 i:56a9 {200000000001} [ ETag:0x12f800000001, Content-Format:application/json, Block2:1/_/1024, Size2:1927 ] :: 'mequality":0}},"Counterx2":{"InputType":"Double Counter","State":0,"LiveCount":0,"Quality":0,"Timestamp":{"secs":0

Jan 01 00:00:54.485 Warn[___] Data body updated during receipt - new request started
v:1 t:NON c:GET i:56ac {03} [ Uri-Path:datatest, Uri-Path:container, 18:, 22:\x23\x54\x65\x73\x74, Block2:0/_/1024, Request-Tag:0x08cdb800 ]

Jan 01 00:00:54.991 dbg [___] call custom handler for resource 'datatest/container' (3)
Jan 01 00:00:54.267 dbg [___] *  [0.0.0.0]:52362 <-> [224.0.1.187]:5683 UDP : netif: sent   40 bytes
v:1 t:NON c:GET i:56ac {03} [ Uri-Path:datatest, Uri-Path:container, 18:, 22:\x23\x54\x65\x73\x74, Block2:0/_/1024, Request-Tag:0x08cdb800 ]

v:1 t:NON c:2.05 i:56aa {02} [ ETag:0x12f800000001, Content-Format:application/json, Block2:0/M/1024, Size2:1927 ] :: '{"Step Inputs":false,"Inputx1":{"InputType":"Single Input","State":0,"Quality":0,"Timestamp":{"secs":0,"nsecs":0,"timequalit

Jan 01 00:00:54.572 dbg [___] ** [0.0.0.0]:52362 <-> [224.0.1.187]:5683 UDP : large body receive internal issue
Jan 01 00:00:54.802 dbg [___] ** [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : lg_xmit 0x80007e10 released
Jan 01 00:00:54.835 dbg [___] ***EVENT: COAP_EVENT_XMIT_BLOCK_FAIL
Jan 01 00:00:54.866 dbg [___] PDU presented by app.
v:1 t:NON c:2.05 i:56ac {03} [ ETag:0x1b7400000001, Content-Format:application/json, Block2:0/M/1024 ] :: '{"Step Inputs":false,"Inputx1":{"InputType":"Single Input","State":0,"Quality":0,"Timestamp":{"secs":0,"nsecs":0,"timequality":0}},"Inpu

Jan 01 00:00:54.968 dbg [___] ** [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : lg_xmit 0x80007e10 initialized
Jan 01 00:00:54.388 dbg [___]    [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : mid=0x56ac: mcast response delayed for 0.034 secs
Jan 01 00:00:54.435 dbg [___] ** [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : mid=0x56ac: added to retransmit queue (34ms)
Jan 01 00:00:54.250 dbg [___] ***EVENT: COAP_EVENT_MSG_RETRANSMITTED
Jan 01 00:00:54.286 dbg [___] ** [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : mid=0x56ab: mcast delayed transmission
v:1 t:NON c:2.05 i:56ab {400000000001} [ ETag:0x1b7400000001, Content-Format:application/json, Block2:1/_/1024, Size2:1927 ] :: 'mequality":0}},"Counterx2":{"InputType":"Double Counter","State":0,"LiveCount":0,"Quality":0,"Timestamp":{"secs":0

Jan 01 00:00:54.797 dbg [___] found Block option, block size is 1024, block nr. 1
Jan 01 00:00:54.003 dbg [___] *  [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : netif: sent  928 bytes
v:1 t:NON c:2.05 i:56ab {400000000001} [ ETag:0x1b7400000001, Content-Format:application/json, Block2:1/_/1024, Size2:1927 ] :: 'mequality":0}},"Counterx2":{"InputType":"Double Counter","State":0,"LiveCount":0,"Quality":0,"Timestamp":{"secs":0

v:1 t:NON c:2.05 i:56ab {400000000001} [ ETag:0x12f800000001, Content-Format:application/json, Block2:1/_/1024, Size2:1927 ] :: 'mequality":0}},"Counterx2":{"InputType":"Double Counter","State":0,"LiveCount":0,"Quality":0,"Timestamp":{"secs":0

Jan 01 00:00:54.325 Warn[___] Data body updated during receipt - new request started
v:1 t:NON c:GET i:56ad {04} [ Uri-Path:datatest, Uri-Path:container, 18:, 22:\x23\x54\x65\x73\x74, Block2:0/_/1024, Request-Tag:0x08cdb800 ]

Jan 01 00:00:54.904 dbg [___] call custom handler for resource 'datatest/container' (3)
Jan 01 00:00:54.253 dbg [___] *  [0.0.0.0]:52362 <-> [224.0.1.187]:5683 UDP : netif: sent   40 bytes
v:1 t:NON c:GET i:56ad {04} [ Uri-Path:datatest, Uri-Path:container, 18:, 22:\x23\x54\x65\x73\x74, Block2:0/_/1024, Request-Tag:0x08cdb800 ]

v:1 t:NON c:2.05 i:56ac {03} [ ETag:0x12f800000001, Content-Format:application/json, Block2:0/M/1024, Size2:1927 ] :: '{"Step Inputs":false,"Inputx1":{"InputType":"Single Input","State":0,"Quality":0,"Timestamp":{"secs":0,"nsecs":0,"timequalit

Jan 01 00:00:54.566 dbg [___] ** [0.0.0.0]:52362 <-> [224.0.1.187]:5683 UDP : large body receive internal issue
Jan 01 00:00:54.062 dbg [___] ** [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : lg_xmit 0x80007e10 released
Jan 01 00:00:54.720 dbg [___] ***EVENT: COAP_EVENT_XMIT_BLOCK_FAIL
Jan 01 00:00:54.753 dbg [___] PDU presented by app.
v:1 t:NON c:2.05 i:56ad {04} [ ETag:0x1b7400000001, Content-Format:application/json, Block2:0/M/1024 ] :: '{"Step Inputs":false,"Inputx1":{"InputType":"Single Input","State":0,"Quality":0,"Timestamp":{"secs":0,"nsecs":0,"timequality":0}},"Inpu

Jan 01 00:00:54.845 dbg [___] ** [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : lg_xmit 0x80007e10 initialized
Jan 01 00:00:54.959 dbg [___]    [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : mid=0x56ad: mcast response delayed for 0.029 secs
Jan 01 00:00:54.004 dbg [___] ** [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : mid=0x56ad: added to retransmit queue (29ms)
Jan 01 00:00:54.258 dbg [___] ***EVENT: COAP_EVENT_MSG_RETRANSMITTED
Jan 01 00:00:54.297 dbg [___] ** [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : mid=0x56ac: mcast delayed transmission
v:1 t:NON c:2.05 i:56ac {03} [ ETag:0x1b7400000001, Content-Format:application/json, Block2:0/M/1024, Size2:1927 ] :: '{"Step Inputs":false,"Inputx1":{"InputType":"Single Input","State":0,"Quality":0,"Timestamp":{"secs":0,"nsecs":0,"timequalit

Jan 01 00:00:54.778 dbg [___] ** [0.0.0.0]:52362 <-> [224.0.1.187]:5683 UDP : large body receive internal issue
Jan 01 00:00:54.935 dbg [___] *  [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : netif: sent 1044 bytes
v:1 t:NON c:2.05 i:56ac {03} [ ETag:0x1b7400000001, Content-Format:application/json, Block2:0/M/1024, Size2:1927 ] :: '{"Step Inputs":false,"Inputx1":{"InputType":"Single Input","State":0,"Quality":0,"Timestamp":{"secs":0,"nsecs":0,"timequalit

v:1 t:NON c:2.05 i:56ad {04} [ ETag:0x12f800000001, Content-Format:application/json, Block2:0/M/1024, Size2:1927 ] :: '{"Step Inputs":false,"Inputx1":{"InputType":"Single Input","State":0,"Quality":0,"Timestamp":{"secs":0,"nsecs":0,"timequalit

Jan 01 00:00:54.282 dbg [___] ** [0.0.0.0]:52362 <-> [224.0.1.187]:5683 UDP : large body receive internal issue
Jan 01 00:00:54.231 dbg [___] ***EVENT: COAP_EVENT_MSG_RETRANSMITTED
Jan 01 00:00:54.269 dbg [___] ** [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : mid=0x56ad: mcast delayed transmission
v:1 t:NON c:2.05 i:56ad {04} [ ETag:0x1b7400000001, Content-Format:application/json, Block2:0/M/1024, Size2:1927 ] :: '{"Step Inputs":false,"Inputx1":{"InputType":"Single Input","State":0,"Quality":0,"Timestamp":{"secs":0,"nsecs":0,"timequalit

Jan 01 00:00:54.641 dbg [___] ** [0.0.0.0]:52362 <-> [224.0.1.187]:5683 UDP : large body receive internal issue
Jan 01 00:00:54.793 dbg [___] *  [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : netif: sent 1044 bytes
v:1 t:NON c:2.05 i:56ad {04} [ ETag:0x1b7400000001, Content-Format:application/json, Block2:0/M/1024, Size2:1927 ] :: '{"Step Inputs":false,"Inputx1":{"InputType":"Single Input","State":0,"Quality":0,"Timestamp":{"secs":0,"nsecs":0,"timequalit

mirrored GET response timed out (0.200 sec)
../../Plugin_DataTest/tests/coap_json_tests.c:494:Mirrored GET Multicast Multiblock :FAIL: Expected -1 to be not equal to -1. Timeout / Empty Queue
[Test] tear down
Jan 01 00:00:54.612 dbg [___] ** [0.0.0.0]:52362 <-> [224.0.1.187]:5683 UDP : lg_crcv 0x800049dc released
Jan 01 00:00:54.698 dbg [___] ***[0.0.0.0]:52362 <-> [224.0.1.187]:5683 UDP : session 0x8004262c: closed
 (303 ms)

-----------------------
1 Tests 1 Failures 0 Ignored
FAIL
Set 'CoAP+JSON' Finished

--- Running set: Serialisation ... all skipped
~~~~~~~~~~~~~~~~~~~~    Summary    ~~~~~~~~~~~~~~~~~~~~
Run: filter 'Multicast Multiblock'
Set: CoAP+JSON
  1: FAILED (303 ms) Mirrored GET Multicast Multiblock
   : 1 ran (303 ms) 0 pass, 0 skipped/broken, 1 failed

Total: 1 ran (1 sec) 0 pass, 0 skipped/broken, 1 failed
~~~~~~~~~~~~~~~~~~~~   Tests End   ~~~~~~~~~~~~~~~~~~~~

Jan 01 00:01:03.276 dbg [___] ***EVENT: COAP_EVENT_SERVER_SESSION_DEL
Jan 01 00:01:03.403 dbg [___] ***[192.168.100.1]:5683 <-> [192.168.100.1]:52359 (if2) UDP : session 0x800430cc: closed
Jan 01 00:01:04.253 dbg [___] ***EVENT: COAP_EVENT_SERVER_SESSION_DEL
Jan 01 00:01:04.345 dbg [___] ***[192.168.100.1]:5683 <-> [192.168.100.1]:52360 (if2) UDP : session 0x80042c8c: closed
Jan 01 00:01:04.256 dbg [___] ***EVENT: COAP_EVENT_SERVER_SESSION_DEL
Jan 01 00:01:04.302 dbg [___] ***[192.168.100.1]:5683 <-> [192.168.100.1]:52361 (if2) UDP : session 0x80042a6c: closed
Jan 01 00:01:23.293 dbg [___] ***EVENT: COAP_EVENT_SERVER_SESSION_DEL
Jan 01 00:01:23.417 dbg [___] ***[192.168.3.5]:5683 <-> [192.168.3.1]:53930 (if3) UDP : session 0x8004284c: closed
Jan 01 00:01:24.274 dbg [___] ***EVENT: COAP_EVENT_SERVER_SESSION_DEL
Jan 01 00:01:24.366 dbg [___] ** [224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : lg_xmit 0x80007e10 released
Jan 01 00:01:24.412 dbg [___] ***[224.0.1.187]:5683 <-> [192.168.100.1]:52362 (if2) UDP : session 0x8004240c: closed

**Comment by cdurkin** [comment]
Thanks very much for the fix, this has fixed the problem.

I just deleted a comment were i thought the problem still existed (which i presume you may have got a notification for) but turns out that I just hadn't merged in the changes correctly and i'd missed the copy of the source address to the session in coap_recvc(). Once i'd corrected that my test is now passing.

Feel free to close this issue

**Comment by mrdeep1** [comment]
Thanks for the confirmation that all is now working as expected. 

Just to double check, was it just your change to` coap_recvc()` that needed the address copy, or have I missed something that needs to be done in the standard LwIP `coap_recvc()`?

**Comment by cdurkin** [comment]
I believe coap_io_lwip.c: coap_recv() is fine, i can't test it as we have replaced that function as described in the OP but it was the fact i hadn't copied the address copy over to our replacement for coap_recv() that caused my first test to fail, so i think that proves that coap_io_lwip.c: coap_recv() is fine (would work if i used it).

Thanks for doing the fix :)

**Comment by mrdeep1** [comment]
Thanks for confirming that.  It did work fine for me with a LwIP client using the standard` coap_recv()`, but I could have missed an edge case.
