### ISSUE TITLE
Segfault in multithreaded C# application when using DTLS and actively disconnecting sessions

### ISSUE THREAD

**Issue by anyc** [obgm/libcoap#1817]
Hello,

we are currently experiencing a sporadic issue with current `develop` branch where a segfault occurs in our C# application (using a custom wrapper for libcoap). Every second, this application starts a new session to GET a resource on a different device and actively closes the session afterwards using `coap_session_disconnected(session, coap_nack_reason_t.COAP_NACK_RST);`. For the event loop, a separate thread is started that repeatedly calls `coap_io_process(ctx, 1000);`. After repeating this for a few seconds, the application crashes with a segfault and the following stack trace:

```
#0  0x00007fffeeeedb94 in BIO_test_flags () from /lib/x86_64-linux-gnu/libcrypto.so.3
#1  0x00007fffeeeeebfe in BIO_copy_next_retry () from /lib/x86_64-linux-gnu/libcrypto.so.3
#2  0x00007fffeeee993b in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.3
#3  0x00007fffeeeee2a2 in BIO_ctrl () from /lib/x86_64-linux-gnu/libcrypto.so.3
#4  0x00007ffff452f697 in ?? () from /lib/x86_64-linux-gnu/libssl.so.3
#5  0x00007ffff452f79b in ?? () from /lib/x86_64-linux-gnu/libssl.so.3
#6  0x00007ffff44e13e5 in ?? () from /lib/x86_64-linux-gnu/libssl.so.3
#7  0x00007ffff45dc07d in coap_dtls_handle_timeout (session=0x555555f5bb10)
    at /projects/github/libcoap/src/coap_openssl.c:3748
#8  0x00007ffff4598206 in coap_io_prepare_io_lkd (ctx=0x555555d20140, sockets=0x7fffef7fa2d0, max_sockets=1, num_sockets=0x7fffef7fa298, 
    now=21958) at /projects/github/libcoap/src/coap_io.c:549
#9  0x00007ffff45974ce in coap_io_prepare_epoll_lkd (ctx=0x555555d20140, now=21958)
    at /projects/github/libcoap/src/coap_io.c:233
#10 0x00007ffff459fc7d in coap_io_do_epoll_lkd (ctx=0x555555d20140, events=0x7fffef7fa3c0, nevents=0)
    at /projects/github/libcoap/src/coap_net.c:2870
#11 0x00007ffff4598c1b in coap_io_process_with_fds_lkd (ctx=0x555555d20140, timeout_ms=1000, enfds=0, ereadfds=0x0, ewritefds=0x0, 
    eexceptfds=0x0) at /projects/github/libcoap/src/coap_io_posix.c:458
#12 0x00007ffff4598a38 in coap_io_process_lkd (ctx=0x555555d20140, timeout_ms=1000)
    at /projects/github/libcoap/src/coap_io_posix.c:147
#13 0x00007ffff45989f8 in coap_io_process (ctx=0x555555d20140, timeout_ms=1000)
    at /projects/github/libcoap/src/coap_io_posix.c:140
```

ENABLE_THREAD_SAFE is on. This happens on Linux and (probably) on Windows. In the latter case, I am not sure because we can't get usable debug output so far.

I started to investigate this issue but it looks like both threads (`coap_io_prepare_io_lkd` and `coap_session_disconnected`) are protected by lock. I will try to find out more but I would like to know if you might already have an idea?

Thank you!

**Comment by anyc** [comment]
Ah, I forgot to say that the assert
```
assert(ssl != NULL && session->state == COAP_SESSION_STATE_HANDSHAKE);
```
in `coap_dtls_handle_timeout` also caused an abort at least once. Hence, I guessed that there is an issue due to multithreading.

**Comment by mrdeep1** [comment]
In` coap_dtls_handle_timeout()`,  It looks like you are disabling the `assert()` checks, `session->tls` has been cleared out due to a previous disconnect, so `ssl` is NULL and hence `DTLSv1_handle_timeout(ssl)` goes off into the weeds.

I would simply check if `ssl` is NULL, early in the i`f{}` statement, in which case do not `call DTLSv1_handle_timeout()` if` ssl` is NULL.

**Comment by mrdeep1** [comment]
If you are building the code with `NDEBUG `defined, then the assert() statement is a no-op.

i.e. .`/configure --disable-assert`

**Comment by anyc** [comment]
I am building with CMake and `-DCMAKE_BUILD_TYPE=Debug` in this case and it looks like there is no option to disable assert. In case you looked at the line numbers, they might be slightly off because I added some debug output. If `ssl` would be NULL, I would have seen a log message.

This is the trace with 9f6e6718 and without my changes:
```
#6  0x00007ffff7c3b517 in __assert_fail (assertion=0x7ffff45ef658 "ssl != NULL && session->state == COAP_SESSION_STATE_HANDSHAKE", 
    file=0x7ffff45ef1e0 "/projects/github/libcoap/src/coap_openssl.c", line=3742, 
    function=0x7ffff45efaf0 <__PRETTY_FUNCTION__.9> "coap_dtls_handle_timeout") at ./assert/assert.c:105
#7  0x00007ffff45dc6ff in coap_dtls_handle_timeout (session=0x555555f76cd0)
    at /projects/github/libcoap/src/coap_openssl.c:3742
#8  0x00007ffff4598963 in coap_io_prepare_io_lkd (ctx=0x555555cb8cf0, sockets=0x7fffefbfc2d0, max_sockets=1, num_sockets=0x7fffefbfc298, 
    now=86482) at /projects/github/libcoap/src/coap_io.c:549
#9  0x00007ffff4597c2b in coap_io_prepare_epoll_lkd (ctx=0x555555cb8cf0, now=86482)
    at /projects/github/libcoap/src/coap_io.c:233
#10 0x00007ffff45a03da in coap_io_do_epoll_lkd (ctx=0x555555cb8cf0, events=0x7fffefbfc3c0, nevents=0)
    at /projects/github/libcoap/src/coap_net.c:2870
#11 0x00007ffff4599378 in coap_io_process_with_fds_lkd (ctx=0x555555cb8cf0, timeout_ms=1000, enfds=0, ereadfds=0x0, ewritefds=0x0, 
    eexceptfds=0x0) at /projects/github/libcoap/src/coap_io_posix.c:458
#12 0x00007ffff4599195 in coap_io_process_lkd (ctx=0x555555cb8cf0, timeout_ms=1000)
    at /projects/github/libcoap/src/coap_io_posix.c:147
#13 0x00007ffff4599155 in coap_io_process (ctx=0x555555cb8cf0, timeout_ms=1000)
    at /projects/github/libcoap/src/coap_io_posix.c:140
```
The assert triggers an abort because `session->state` is `COAP_SESSION_STATE_NONE`.

**Comment by anyc** [comment]
This is the debug log:

```
Dez 04 18:13:51.479 DEBG ** 10.3.147.253:57913 <-> 192.168.10.4:5684 DTLS: mid=0xa19f: not transmitted after disconnect
Dez 04 18:13:51.479 DEBG ***10.3.147.253:57913 <-> 192.168.10.4:5684 DTLS: session disconnected (COAP_NACK_RST)
Dez 04 18:13:51.479 DEBG ***EVENT: COAP_EVENT_DTLS_CLOSED
Dez 04 18:13:51.479 DEBG ***10.3.147.253:60369 <-> 192.168.10.4:5684 DTLS: new outgoing session
Dez 04 18:13:51.479 DEBG CoAP Client restricted to (D)TLS1.2 with Identity Hint callback
Dez 04 18:13:51.479 DEBG *  10.3.147.253:60369 <-> 192.168.10.4:5684 DTLS: netif: sent  247 bytes
Dez 04 18:13:51.480 DEBG ** 10.3.147.253:60369 <-> 192.168.10.4:5684 DTLS: mid=0x5b3b: delayed

Dez 04 18:13:52.479 DEBG ** 10.3.147.253:60369 <-> 192.168.10.4:5684 DTLS: DTLS retransmit timeout
Dez 04 18:13:52.479 DEBG *  10.3.147.253:60369 <-> 192.168.10.4:5684 DTLS: netif: sent  247 bytes
Dez 04 18:13:52.480 DEBG ** 10.3.147.253:60369 <-> 192.168.10.4:5684 DTLS: mid=0x5b3b: not transmitted after disconnect
Dez 04 18:13:52.480 DEBG ***10.3.147.253:60369 <-> 192.168.10.4:5684 DTLS: session disconnected (COAP_NACK_RST)
Dez 04 18:13:52.480 DEBG ***EVENT: COAP_EVENT_DTLS_CLOSED
Dez 04 18:13:52.480 DEBG ***10.3.147.253:54725 <-> 192.168.10.4:5684 DTLS: new outgoing session
Dez 04 18:13:52.480 DEBG CoAP Client restricted to (D)TLS1.2 with Identity Hint callback
Dez 04 18:13:52.480 DEBG *  10.3.147.253:54725 <-> 192.168.10.4:5684 DTLS: netif: sent  247 bytes
Dez 04 18:13:52.480 DEBG ** 10.3.147.253:54725 <-> 192.168.10.4:5684 DTLS: mid=0x363d: delayed

Dez 04 18:13:53.480 DEBG ** 10.3.147.253:54725 <-> 192.168.10.4:5684 DTLS: DTLS retransmit timeout
Dez 04 18:13:53.480 DEBG *  10.3.147.253:54725 <-> 192.168.10.4:5684 DTLS: netif: sent  247 bytes
Dez 04 18:13:53.480 DEBG ** 10.3.147.253:54725 <-> 192.168.10.4:5684 DTLS: mid=0x363d: not transmitted after disconnect
Dez 04 18:13:53.480 DEBG ***10.3.147.253:54725 <-> 192.168.10.4:5684 DTLS: session disconnected (COAP_NACK_RST)
Dez 04 18:13:53.480 DEBG ***EVENT: COAP_EVENT_DTLS_CLOSED
Dez 04 18:13:53.481 DEBG ***10.3.147.253:60495 <-> 192.168.10.4:5684 DTLS: new outgoing session
Dez 04 18:13:53.481 DEBG CoAP Client restricted to (D)TLS1.2 with Identity Hint callback
Dez 04 18:13:53.481 DEBG *  10.3.147.253:60495 <-> 192.168.10.4:5684 DTLS: netif: sent  247 bytes
Dez 04 18:13:53.481 DEBG ** 10.3.147.253:60495 <-> 192.168.10.4:5684 DTLS: mid=0x0467: delayed

Dez 04 18:13:54.481 DEBG ** 10.3.147.253:60495 <-> 192.168.10.4:5684 DTLS: DTLS retransmit timeout
Dez 04 18:13:54.481 DEBG *  10.3.147.253:60495 <-> 192.168.10.4:5684 DTLS: netif: sent  247 bytes
Dez 04 18:13:54.481 DEBG ** 10.3.147.253:60495 <-> 192.168.10.4:5684 DTLS: mid=0x0467: not transmitted after disconnect
Dez 04 18:13:54.481 DEBG ***10.3.147.253:60495 <-> 192.168.10.4:5684 DTLS: session disconnected (COAP_NACK_RST)
Dez 04 18:13:54.481 DEBG ***EVENT: COAP_EVENT_DTLS_CLOSED
Dez 04 18:13:54.481 DEBG ***10.3.147.253:38694 <-> 192.168.10.4:5684 DTLS: new outgoing session
Dez 04 18:13:54.481 DEBG CoAP Client restricted to (D)TLS1.2 with Identity Hint callback
Dez 04 18:13:54.481 DEBG *  10.3.147.253:38694 <-> 192.168.10.4:5684 DTLS: netif: sent  247 bytes
Dez 04 18:13:54.481 DEBG ** 10.3.147.253:38694 <-> 192.168.10.4:5684 DTLS: mid=0x2a39: delayed

Dez 04 18:13:55.481 DEBG ** 10.3.147.253:38694 <-> 192.168.10.4:5684 DTLS: mid=0x2a39: not transmitted after disconnect
Dez 04 18:13:55.482 DEBG ***10.3.147.253:38694 <-> 192.168.10.4:5684 DTLS: session disconnected (COAP_NACK_RST)
Dez 04 18:13:55.482 DEBG ** 10.3.147.253:38694 <-> 192.168.10.4:5684 DTLS: DTLS retransmit timeout
Dez 04 18:13:55.482 DEBG ***EVENT: COAP_EVENT_DTLS_CLOSED
mono: /projects/github/libcoap/src/coap_openssl.c:3742: coap_dtls_handle_timeout: Assertion `ssl != NULL && session-info: 
>state == COAP_SESSION_STATE_HANDSHAKE' failed.
Dez 04 18:13:55.482 DEBG ***10.3.147.253:41316 <-> 192.168.10.4:5684 DTLS: new outgoing session
Dez 04 18:13:55.482 DEBG CoAP Client restricted to (D)TLS1.2 with Identity Hint callback
Dez 04 18:13:55.482 DEBG *  10.3.147.253:41316 <-> 192.168.10.4:5684 DTLS: netif: sent  247 bytes
Dez 04 18:13:55.482 DEBG ** 10.3.147.253:41316 <-> 192.168.10.4:5684 DTLS: mid=0x0db9: delayed
```

**Comment by mrdeep1** [comment]
Note the ordering difference
````
Dez 04 18:13:54.481 DEBG ** 10.3.147.253:60495 <-> 192.168.10.4:5684 DTLS: DTLS retransmit timeout
Dez 04 18:13:54.481 DEBG *  10.3.147.253:60495 <-> 192.168.10.4:5684 DTLS: netif: sent  247 bytes
Dez 04 18:13:54.481 DEBG ** 10.3.147.253:60495 <-> 192.168.10.4:5684 DTLS: mid=0x0467: not transmitted after disconnect
Dez 04 18:13:54.481 DEBG ***10.3.147.253:60495 <-> 192.168.10.4:5684 DTLS: session disconnected (COAP_NACK_RST)
Dez 04 18:13:54.481 DEBG ***EVENT: COAP_EVENT_DTLS_CLOSED
````

````
Dez 04 18:13:55.481 DEBG ** 10.3.147.253:38694 <-> 192.168.10.4:5684 DTLS: mid=0x2a39: not transmitted after disconnect
Dez 04 18:13:55.482 DEBG ***10.3.147.253:38694 <-> 192.168.10.4:5684 DTLS: session disconnected (COAP_NACK_RST)
Dez 04 18:13:55.482 DEBG ** 10.3.147.253:38694 <-> 192.168.10.4:5684 DTLS: DTLS retransmit timeout
Dez 04 18:13:55.482 DEBG ***EVENT: COAP_EVENT_DTLS_CLOSED
mono: /projects/github/libcoap/src/coap_openssl.c:3742: coap_dtls_handle_timeout: Assertion `ssl != NULL && session-info: 
>state == COAP_SESSION_STATE_HANDSHAKE' failed.
````

which I think has something to do with this.  In the latter, the `session disconnected `comes before the `DTLS retransmit timeout` which is likely to cause `session->state is COAP_SESSION_STATE_NONE`

It could be that 2 different threads are doing things here.

If you define COAP_THREAD_NUM_LOGGING when building the code, this may give a clue.

**Comment by anyc** [comment]
Hm, this was enabled `-- ENABLE_THREAD_NUM_LOGGING........ON`. I also explicitly enabled it but I see no difference in the output. It looks like this does not get enabled:

`include/coap3/coap_defines.h:/* #undef COAP_THREAD_NUM_LOGGING */`

I will check this again tomorrow, I have to leave now. Thank you!

**Comment by anyc** [comment]
I got a few more minutes... I built the library with configure and now I get the thread id in the output:
```
Dez 04 18:53:22.326  1 DEBG ***10.3.147.253:37411 <-> 192.168.10.4:5684 DTLS: new outgoing session
Dez 04 18:53:22.326  1 DEBG CoAP Client restricted to (D)TLS1.2 with Identity Hint callback
Dez 04 18:53:22.326  1 DEBG *  10.3.147.253:37411 <-> 192.168.10.4:5684 DTLS: netif: sent  247 bytes
Dez 04 18:53:22.326  1 DEBG ** 10.3.147.253:37411 <-> 192.168.10.4:5684 DTLS: mid=0x848f: delayed
Dez 04 18:53:23.326  1 DEBG ** 10.3.147.253:37411 <-> 192.168.10.4:5684 DTLS: mid=0x848f: not transmitted after disconnect
Dez 04 18:53:23.326  1 DEBG ***10.3.147.253:37411 <-> 192.168.10.4:5684 DTLS: session disconnected (COAP_NACK_RST)
Dez 04 18:53:23.326  1 DEBG ***EVENT: COAP_EVENT_DTLS_CLOSED
Dez 04 18:53:23.326  1 DEBG ***10.3.147.253:59920 <-> 192.168.10.4:5684 DTLS: new outgoing session
Dez 04 18:53:23.326  1 DEBG CoAP Client restricted to (D)TLS1.2 with Identity Hint callback
Dez 04 18:53:23.326  1 DEBG *  10.3.147.253:59920 <-> 192.168.10.4:5684 DTLS: netif: sent  247 bytes
Dez 04 18:53:23.326  1 DEBG ** 10.3.147.253:59920 <-> 192.168.10.4:5684 DTLS: mid=0x4b8e: delayed
Dez 04 18:53:24.327  1 DEBG ** 10.3.147.253:59920 <-> 192.168.10.4:5684 DTLS: mid=0x4b8e: not transmitted after disconnect
Dez 04 18:53:24.327  1 DEBG ***10.3.147.253:59920 <-> 192.168.10.4:5684 DTLS: session disconnected (COAP_NACK_RST)
Dez 04 18:53:24.327  1 DEBG ***EVENT: COAP_EVENT_DTLS_CLOSED
Dez 04 18:53:24.327  1 DEBG ***10.3.147.253:50462 <-> 192.168.10.4:5684 DTLS: new outgoing session
Dez 04 18:53:24.327  1 DEBG CoAP Client restricted to (D)TLS1.2 with Identity Hint callback
Dez 04 18:53:24.327  1 DEBG *  10.3.147.253:50462 <-> 192.168.10.4:5684 DTLS: netif: sent  247 bytes
Dez 04 18:53:24.327  1 DEBG ** 10.3.147.253:50462 <-> 192.168.10.4:5684 DTLS: mid=0x59f7: delayed
Dez 04 18:53:25.327  1 DEBG ** 10.3.147.253:50462 <-> 192.168.10.4:5684 DTLS: mid=0x59f7: not transmitted after disconnect
Dez 04 18:53:25.327  1 DEBG ***10.3.147.253:50462 <-> 192.168.10.4:5684 DTLS: session disconnected (COAP_NACK_RST)
Dez 04 18:53:25.327  1 DEBG ***EVENT: COAP_EVENT_DTLS_CLOSED
Dez 04 18:53:25.327  1 DEBG ***10.3.147.253:39287 <-> 192.168.10.4:5684 DTLS: new outgoing session
Dez 04 18:53:25.327  1 DEBG CoAP Client restricted to (D)TLS1.2 with Identity Hint callback
Dez 04 18:53:25.328  1 DEBG *  10.3.147.253:39287 <-> 192.168.10.4:5684 DTLS: netif: sent  247 bytes
Dez 04 18:53:25.328  1 DEBG ** 10.3.147.253:39287 <-> 192.168.10.4:5684 DTLS: mid=0x9873: delayed
Dez 04 18:53:26.327  2 DEBG ** 10.3.147.253:39287 <-> 192.168.10.4:5684 DTLS: DTLS retransmit timeout
Dez 04 18:53:26.327  2 DEBG *  10.3.147.253:39287 <-> 192.168.10.4:5684 DTLS: netif: sent  247 bytes
Dez 04 18:53:26.328  1 DEBG ** 10.3.147.253:39287 <-> 192.168.10.4:5684 DTLS: mid=0x9873: not transmitted after disconnect
Dez 04 18:53:26.328  1 DEBG ***10.3.147.253:39287 <-> 192.168.10.4:5684 DTLS: session disconnected (COAP_NACK_RST)
Dez 04 18:53:26.328  1 DEBG ***EVENT: COAP_EVENT_DTLS_CLOSED
Dez 04 18:53:26.328  1 WARN ***10.3.147.253:52980 <-> 192.168.10.4:5684 DTLS: session 0x555555fa8150: duplicate - already exists
Dez 04 18:53:26.328  1 DEBG ***10.3.147.253:52980 <-> 192.168.10.4:5684 DTLS: session 0x555555fa8150: closed

```

But with a strange backtrace:
```
(gdb) back
#0  0x000000004005774e in ?? ()
#1  0x00007ffff7218850 in ?? ()
#2  0x0000000000000001 in ?? ()
#3  0x0000000000000000 in ?? ()
```
I will check this again tomorrow.

**Comment by mrdeep1** [comment]
For the backtrace, as you have multiple threads, you need to do something like
````
(gdb) thread apply all back
````
It is worth trying this change
````
diff --git a/src/coap_openssl.c b/src/coap_openssl.c
index d19fda68..14777d4b 100644
--- a/src/coap_openssl.c
+++ b/src/coap_openssl.c
@@ -3739,14 +3739,16 @@ int
 coap_dtls_handle_timeout(coap_session_t *session) {
   SSL *ssl = (SSL *)session->tls;

-  assert(ssl != NULL && session->state == COAP_SESSION_STATE_HANDSHAKE);
-  if ((++session->dtls_timeout_count > session->max_retransmit) ||
-      (DTLSv1_handle_timeout(ssl) < 0)) {
-    /* Too many retries */
-    coap_session_disconnected_lkd(session, COAP_NACK_TLS_FAILED);
-    return 1;
+  if (ssl != NULL && session->state == COAP_SESSION_STATE_HANDSHAKE) {
+    if ((++session->dtls_timeout_count > session->max_retransmit) ||
+        (DTLSv1_handle_timeout(ssl) < 0)) {
+      /* Too many retries */
+      coap_session_disconnected_lkd(session, COAP_NACK_TLS_FAILED);
+      return 1;
+    }
+    return 0;
   }
-  return 0;
+  return 1;
 }

 #if COAP_SERVER_SUPPORT
````

I have pushed a PR to fix the cmake COAP_THREAD_NUM_LOGGING issue.

**Comment by anyc** [comment]
I noticed that `COAP_THREAD_NUM_LOGGING` is still not in effect. After the patch in #1819, the application runs longer until it segfaults but it is a different stacktrace now. I will check if this is the fault of the application now. I think this issue can be closed with #1819.

**Comment by mrdeep1** [comment]
I think that is also worth trying the suggested change at https://github.com/obgm/libcoap/issues/1817#issuecomment-3613679641 to see if that failure now goes away.

**Comment by anyc** [comment]
This is fixed with the latest fixes. Thank you!
