### ISSUE TITLE
don't succeed in building on Windows

### ISSUE THREAD

**Issue by vdaele** [obgm/libcoap#267]
Probably a stupid question but I don't succeed in building on Windows.

Should I install mingw and/or msys? 32 or 64bit versions?
I almost reached the end of the ./configure but then I ran into an unsupported platform.

Or should I open  win32/libcoap/libcoap in VisualStudio? This way I run into 
 "Cannot open include file: 'openssl/ssl.h'"  (preferably I want to build with DTLS but building with OpenSSL is also fine though I'm not sure how to install it on Windows)

so I'm a bit lost :-(

**Comment by obgm** [comment]
Currently, the only supported way to build this library on Windows is in visual studio using the included project file. Unfortunately, it expects OpenSSL to be installed in a non-standard location (IIRC in the libcoap package's root directory). You may need to adjust the path in the configuration dialog.

Regarding cygwin and mingw: The configure script currently does not know anything about cygwin and mingw and therefore complains about an unsupport platform. I never bothered to check if anything special needs to be done for these platforms to work.

**Comment by andygikling** [comment]
Actually, it appears to be worse than that @obgm.  I just opened the project in VS2017 and the compiler is not happy with, for example: 

coap_session_type_t : unsigned char

Thoughts?  Have you opened the project in VS2019 and tried to build it recently?

**Comment by mrdeep1** [comment]
@andygikling I created the patch #368 which uses things like `enum coap_session_type_t : unsigned char` following unscoped enum Syntax in https://docs.microsoft.com/en-us/cpp/cpp/enumerations-cpp?view=vs-2017 - which happens to be the same for vs-2019.  

The intent here was to create an enum which has the size of a byte rather than an int to come up with a solution to #292 as in some case the ultimate variable has been only allocated a byte.

Unfortunately I do not have a VS system to compile against to test, so not sure what the compiler is objecting to given that the syntax looks OK.  

If you could try this change (putting everything on one line) and let me know if this works, that would be great.
````
diff --git a/include/coap2/coap_dtls.h b/include/coap2/coap_dtls.h
index 0aeb863..992ca07 100644
--- a/include/coap2/coap_dtls.h
+++ b/include/coap2/coap_dtls.h
@@ -186,8 +186,7 @@ typedef coap_dtls_key_t *(*coap_dtls_sni_callback_t)(const char *sni,
 
 
 #if defined(_MSC_VER)
-typedef enum
-coap_dtls_pki_version_t : unsigned char
+typedef enum coap_dtls_pki_version_t : unsigned char
 #else /* !_MSC_VER */
 typedef enum
 __attribute__ ((__packed__))
diff --git a/include/coap2/coap_session.h b/include/coap2/coap_session.h
index d8e041d..35b1cee 100644
--- a/include/coap2/coap_session.h
+++ b/include/coap2/coap_session.h
@@ -38,8 +38,7 @@ typedef struct coap_fixed_point_t {
 #define COAP_PROTO_RELIABLE(p) ((p)==COAP_PROTO_TCP || (p)==COAP_PROTO_TLS)
 
 #if defined(_MSC_VER)
-typedef enum
-coap_session_type_t : unsigned char
+typedef enum coap_session_type_t : unsigned char
 #else /* !_MSC_VER */
 typedef enum
 __attribute__ ((__packed__))
@@ -51,8 +50,7 @@ __attribute__ ((__packed__))
 } coap_session_type_t;
 
 #if defined(_MSC_VER)
-typedef enum
-coap_session_state_t : unsigned char
+typedef enum coap_session_state_t : unsigned char
 #else /* !_MSC_VER */
 typedef enum
 __attribute__ ((__packed__))
diff --git a/include/coap2/pdu.h b/include/coap2/pdu.h
index aec9f9b..aef7d1a 100644
--- a/include/coap2/pdu.h
+++ b/include/coap2/pdu.h
@@ -340,8 +340,7 @@ coap_pdu_t * coap_pdu_from_pbuf(struct pbuf *pbuf);
 * coap_proto_t values
 */
 #if defined(_MSC_VER)
-typedef enum
-coap_proto_t : unsigned char
+typedef enum coap_proto_t : unsigned char
 #else /* !_MSC_VER */
 typedef enum
 __attribute__ ((__packed__))
````

**Comment by andygikling** [comment]
Thanks for the prompt reply.  I tired putting the typedef on the same line as you suggested.  No luck.

I get all three of these for one of the instances of the correction above:
E0040	expected an identifier	libcoap	C:\Dev\Coap_libcoap\include\coap2\coap_dtls.h	189	
E0065	expected a ';'	libcoap	C:\Dev\Coap_libcoap\include\coap2\coap_dtls.h	194	
C2059	 syntax error: ':'	libcoap	C:\Dev\Coap_libcoap\include\coap2\coap_dtls.h	189	

VS2019 says the solution has 2269 errors.  I guess I'll test this library in Linux for now.

Let us know if anyone gets around to sorting our the win32 platform issues.  I'd love to run this from Visual Studio if possible.

**Comment by andygikling** [comment]
A bit more legwork here.  Most of the error's I'm seeing stem from the error described above, so I think if we can work that out we might close to making it compile. 

However, I'm also seeing these other categories of errors for the win32 platform which are hard for me to explain:

No pthread on Windows, might need a new define:
E1696	cannot open source file "pthread.h"	libcoap	C:\Dev\Coap_libcoap\include\coap2\coap_mutex.h	40

Redefinition of basic type?  Might be an artifact of the main issue:
C2371	 'size_t': redefinition; different basic types
C:\Dev\Coap_libcoap\src\coap_hashkey.c: note: see declaration of 'size_t'	libcoap	C:\Dev\Coap_libcoap\include\coap2\coap_session.h	262

**Comment by obgm** [comment]
@andygikling Yes, when checking with VS, I stumbled across this as well, see [issue 394](https://github.com/obgm/libcoap/issues/394).

**Comment by mrdeep1** [comment]
@andygikling I have just pushed #400 which reverts the #define -> enum change where the enum has to be one byte.  Likewise I have pushed #401 to remove the need for pthread in Windows build.

> Redefinition of basic type? Might be an artifact of the main issue:
> C2371	'size_t': redefinition; different basic types
> C:\Dev\Coap_libcoap\src\coap_hashkey.c: note: see declaration of 'size_t'	libcoap C:\Dev\Coap_libcoap\include\coap2\coap_session.h	262

Not sure about the size_t re-definition issue.  coap_session.h: 262 refers to ssizet (a signed size_t), not size_t 
````
ssize_t coap_session_send(coap_session_t *session,
  const uint8_t *data, size_t datalen);
````

ssize_t is specifically defined for Windows in include/coap2/libcoap.h: 24
````
#if defined(_WIN32)
#pragma comment(lib,"Ws2_32.lib")
#include <ws2tcpip.h>
typedef SSIZE_T ssize_t;
typedef USHORT in_port_t;
#elif !defined (CONTIKI)
````
It could be a compiler wobbly (but unlikely) from all the other errors.  Both of these code fragments have not been changed for a long while, but it could be something introduced by VC2019

**Comment by andygikling** [comment]
Unfortunately, reverting the enum hasn't fix the build win32 build.

We need the mutex fix from #401, after applying that we still have many errors in VS2017 and 2019 that say for example: 

E0020	identifier "coap_endpoint_t" is undefined	libcoap	\include\coap2\coap_session.h	306

I found that if you lead all the coap_subscription_t and coap_endpoint_t with "struct" the compiler is happy with you.  There are dozens of places in the code that require this.  I'm not sure how this might effect other platforms.  I'm also not sure if there is a switch in the compiler to relax this or something.  Thoughts?

Once you get "struct" put in before these variables, I'm down to about 9 errors.

The important ones are:

C2065	'mhdr': undeclared identifier	libcoap	\src\coap_io.c	968

It seems the _WIN32 flag in this file causes you to miss the definition of this variable. 

Also, 

LNK1181	cannot open input file '\win32\x64\Debug DLL\libcoap-2-openssl.lib'	coap-client	\win32\coap-client\LINK	1

Maybe I don't have ssl setup correctly in my environment? Any advice here would be helpful.

**Comment by mrdeep1** [comment]
@andygikling Apologies for all the pain you are having to go through to debug Windows complation.
The coap_endpoint_t and coap_subscription_should be correctly defined when include/coap2/coap_forward_decls.h is included.  It is possible that you may need this change
````
diff --git a/win32/libcoap.vcxproj b/win32/libcoap.vcxproj
index 2a90ee3..3938e16 100644
--- a/win32/libcoap.vcxproj
+++ b/win32/libcoap.vcxproj
@@ -70,6 +70,7 @@
     <ClInclude Include="..\include\coap2\coap_event.h" />
     <ClInclude Include="..\include\coap2\coap_forward_decls.h" />
     <ClInclude Include="..\include\coap2\coap_hashkey.h" />
+    <ClInclude Include="..\include\coap2\coap_internal.h" />
     <ClInclude Include="..\include\coap2\coap_io.h" />
     <ClInclude Include="..\include\coap2\coap_mutex.h" />
     <ClInclude Include="..\include\coap2\coap_session.h" />
diff --git a/win32/libcoap.vcxproj.filters b/win32/libcoap.vcxproj.filters
index 3838d1f..8ae545f 100644
--- a/win32/libcoap.vcxproj.filters
+++ b/win32/libcoap.vcxproj.filters
@@ -110,6 +110,15 @@
     <ClInclude Include="..\include\coap2\coap_event.h">
       <Filter>Header Files</Filter>
     </ClInclude>
+    <ClInclude Include="..\include\coap2\coap_forward_decls.h">
+      <Filter>Header Files</Filter>
+    </ClInclude>
+    <ClInclude Include="..\include\coap2\coap_hashkey.h">
+      <Filter>Header Files</Filter>
+    </ClInclude>
+    <ClInclude Include="..\include\coap2\coap_internal.h">
+      <Filter>Header Files</Filter>
+    </ClInclude>
     <ClInclude Include="..\include\coap2\coap_io.h">
       <Filter>Header Files</Filter>
     </ClInclude>
````

> C2065	'mhdr': undeclared identifier	libcoap	\src\coap_io.c	968
This change should fix this
````
diff --git a/coap_config.h.windows b/coap_config.h.windows
index a734209..e9539a7 100644
--- a/coap_config.h.windows
+++ b/coap_config.h.windows
@@ -66,6 +66,8 @@
 
 #define HAVE_OPENSSL 1
 
+#define HAVE_STRUCT_CMSGHDR 1
+
 /* Define to the address where bug reports for this package should be sent. */
 #define PACKAGE_BUGREPORT "libcoap-developers@lists.sourceforge.net"
 

````

> LNK1181	cannot open input file '\win32\x64\Debug DLL\libcoap-2-openssl.lib'	coap-client \win32\coap-client\LINK	1
There was a previous comment in #144 
````
The path to your installation of OpenSSL is configurable in the “property sheet” tab of visual studio for the libcoap project. Select the properties for libcoap and edit the path in “user macros”.
```

> C2059	syntax error: ')'	libcoap	c:\dev\coap_libcoap2\src\resource.c	655
I think that this one will get sorted out when coap_subscription_t is fixed as above in the vcxproj change.

**Comment by mrdeep1** [comment]
@andygikling PR #402 may fix the current Windows build issues.

**Comment by mrdeep1** [comment]
@andygikling Just updated PR #402 which I can now compile with VS2019 (preferably #404 or #401 also need to be in the code)

**Comment by andygikling** [comment]
Awesome thank you so much.  I'll test it later today and get back to you.

**Comment by mrdeep1** [comment]
@andygikling #404 is now merged into develop, and #402 now includes #404 ready for your testing.

**Comment by andygikling** [comment]
@mrdeep1 - using the patch set from #404 I'm not able to build the win32 platform with VS2019.  Thanks!

**Comment by mrdeep1** [comment]
@andygikling You need to be more explicit with at least the first couple of errors that you are seeing to be able to help you here.  Also, you need #402 which does include the changes of #404 .

**Comment by mrdeep1** [comment]
@andygikling VS2019 & win32 build fine for me with #402 .

**Comment by mrdeep1** [comment]
@vdaele @andygikling  Can this be closed off now?

**Comment by andygikling** [comment]
Yes I would say so!
