### ISSUE TITLE
Only first two blocks are received from large notifications

### ISSUE THREAD

**Issue by matheorsolya** [obgm/libcoap#459]
Consider the following scenario. The client is subscribed to XYZ, when this resource changes a notification is sent the to client. The messages should look like this:
![coap_communication](https://user-images.githubusercontent.com/61309816/75017210-4011f380-5495-11ea-990d-0c2e31af1c03.png)

With current implementation the client receives only the first two blocks (num 0 and num 1). It's like the client is blocked, waiting for an ACK for its first GET request. However this ACK does not exists, only a CON 2.05 is received with the next block. 

My quick fix was to add the following code to the net.c file (in the `coap_dispatch method` in the `case COAP_MESSAGE_CON`):
```C
      if (pdu->code == 69 && session->con_active) {
        session->con_active--;
        if (session->state == COAP_SESSION_STATE_ESTABLISHED)
          /* Flush out any entries on session->delayqueue */
          coap_session_connected(session);
      }
```
This way the CON 2.05 acts as an ACK and the client will not be blocked waiting. 
After adding the suggested fix, the communication went as illustrated on the attached image.

Is there any other solution for this problem? Or should the communication look differently?

**Comment by mrdeep1** [comment]
@matheorsolya THis issue is, I believe, fixed in https://github.com/obgm/libcoap/pull/441 in that my test scenario that is trying to emulate what you are doing fails without #441 installed, but works if it does.

Please let us know if this fixes your issue before I try a more exact emulation of what you are doing.

**Comment by matheorsolya** [comment]
Sadly, #441 does not fix our issue. 
What now I know for sure is that the latest stable version has this issue as well (so does the #441 fix). 

Ps. Sorry for the delayed answer, it took us some time to integrate the updated libcoap.

**Comment by mrdeep1** [comment]
It appears that your server is sending the subsequent blocks with CON set, not contained in the ACK response.
````
Mar 24 10:00:04.861 DEBG *  [::ffff:127.0.0.1]:5683 <-> [::ffff:127.0.0.1]:48490 (if1) UDP : sent 31 bytes
v:1 t:ACK c:2.05 i:9ed9 {} [ ETag:\x1C\xF3\x86\xFC, Content-Format:text/plain, Block2:0/M/16, Size2:53 ] :: '0-23456789012345'
Mar 24 10:00:04.861 DEBG *  [::ffff:127.0.0.1]:5683 <-> [::ffff:127.0.0.1]:48490 (if1) UDP : received 11 bytes
v:1 t:CON c:GET i:9eda {} [ Uri-Path:test, Block2:1/_/16 ]
Mar 24 10:00:04.861 DEBG call custom handler for resource 'test'
Mar 24 10:00:04.861 DEBG *  [::ffff:127.0.0.1]:5683 <-> [::ffff:127.0.0.1]:48490 (if1) UDP : sent 31 bytes
v:1 t:ACK c:2.05 i:9eda {} [ ETag:\x1C\xF3\x86\xFC, Content-Format:text/plain, Block2:1/M/16, Size2:53 ] :: '1-23456789012345'
Mar 24 10:00:04.861 DEBG *  [::ffff:127.0.0.1]:5683 <-> [::ffff:127.0.0.1]:48490 (if1) UDP : received 11 bytes
v:1 t:CON c:GET i:9edb {} [ Uri-Path:test, Block2:2/_/16 ]
Mar 24 10:00:04.861 DEBG call custom handler for resource 'test'
Mar 24 10:00:04.861 DEBG *  [::ffff:127.0.0.1]:5683 <-> [::ffff:127.0.0.1]:48490 (if1) UDP : sent 31 bytes
v:1 t:ACK c:2.05 i:9edb {} [ ETag:\x1C\xF3\x86\xFC, Content-Format:text/plain, Block2:2/M/16, Size2:53 ] :: '3-12345678901234'
Mar 24 10:00:04.862 DEBG *  [::ffff:127.0.0.1]:5683 <-> [::ffff:127.0.0.1]:48490 (if1) UDP : received 11 bytes
v:1 t:CON c:GET i:9edc {} [ Uri-Path:test, Block2:3/_/16 ]
Mar 24 10:00:04.862 DEBG call custom handler for resource 'test'
Mar 24 10:00:04.862 DEBG *  [::ffff:127.0.0.1]:5683 <-> [::ffff:127.0.0.1]:48490 (if1) UDP : sent 20 bytes
v:1 t:ACK c:2.05 i:9edc {} [ ETag:\x1C\xF3\x86\xFC, Content-Format:text/plain, Block2:3/_/16, Size2:53 ] :: '5-3-2'
````
when /test holds the data` 0-234567890123451-234567890123453-123456789012345-3-2`.
<--- CON Block0
---> ACK
---> CON Request Block 1
<--- ACK containing Block 1
---> CON Request Block 2
<--- ACT containing Block 2
is how it should be.  See https://tools.ietf.org/html/rfc7959#section-3.4 which unfortunately does not flag up the CON or ACK flags.  I suggest you use the `coap_add_data_blocked_response()` function for sending the data back from the server where the underlying libcoap handles the BLOCK protocol requirements.  `examples/coap-server.c` shows the usage.

**Comment by mrdeep1** [comment]
@matheorsolya Is this issue still outstanding?  If not, can you please close this issue.

**Comment by obgm** [comment]
Closing off as resolved.
